/**
 * Challenge preset factories.
 *
 * Two built-in presets offered in the Create wizard:
 *  - Classic: mirrors v1 (gym binary, steps counter, junk penalty, weight tracker)
 *  - Minimal: single binary rule — good for simple yes/no challenges
 *
 * Both return a `Rule[]` ready to drop into `ChallengeConfig.rules`.
 * IDs are generated by the caller via nanoid to keep this module Firestore-free.
 */

import type { Rule } from '../../types';

// ---------------------------------------------------------------------------
// Classic preset (v1 parity)
// ---------------------------------------------------------------------------

/**
 * Four-rule preset that mirrors the v1 hardcoded challenge:
 *  1. Gym (binary, 4-day weekly cap, 5 lifetime free passes)
 *  2. Steps (counter, 10 000 steps = 5 pts)
 *  3. Junk (penalty, first infraction each week waived, 5 lifetime free passes)
 *  4. Weight (tracker, up to 30 pts toward personal goal)
 *
 * @param ids Stable IDs for [gym, steps, junk, weight] — generate with nanoid.
 */
export function classicPreset(ids: [string, string, string, string]): Rule[] {
  const [gymId, stepsId, junkId, weightId] = ids;
  return [
    {
      id: gymId,
      kind: 'binary',
      name: 'Gym',
      emoji: '🏋️',
      order: 0,
      pointsYes: 1,
      pointsNo: 0,
      pointsFree: 1,
      freePasses: { count: 5, lifetime: true },
      weeklyCap: { maxScoringDays: 4 },
    },
    {
      id: stepsId,
      kind: 'counter',
      name: 'Steps',
      emoji: '👟',
      order: 1,
      target: 10_000,
      maxPoints: 5,
      unit: 'steps',
      decimals: 0,
    },
    {
      id: junkId,
      kind: 'penalty',
      name: 'Junk Food',
      emoji: '🍔',
      order: 2,
      pointsClean: 1,
      pointsPerInfraction: -1,
      pointsFree: 1,
      weeklyFirstWaived: true,
      freePasses: { count: 5, lifetime: true },
    },
    {
      id: weightId,
      kind: 'tracker',
      name: 'Weight',
      emoji: '⚖️',
      order: 3,
      maxPoints: 30,
      unit: 'lb',
      decimals: 1,
    },
  ];
}

// ---------------------------------------------------------------------------
// Minimal preset
// ---------------------------------------------------------------------------

/**
 * Single binary rule — the simplest possible challenge.
 * Good for "did you do the thing today?" use cases.
 *
 * @param id    Stable ID for the rule — generate with nanoid.
 * @param name  Display name for the rule, e.g. "Workout", "Read", "Meditate".
 * @param emoji Optional emoji for compact display.
 */
export function minimalPreset(id: string, name: string, emoji?: string): Rule[] {
  return [
    {
      id,
      kind: 'binary',
      name,
      emoji,
      order: 0,
      pointsYes: 1,
      pointsNo: 0,
      pointsFree: 1,
      freePasses: null,
      weeklyCap: null,
    },
  ];
}
